name: Deployment Logger

on: 
  deployment_status: {}

permissions:
  contents: write

jobs:
  log-deployment:
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state != 'pending'
    
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
          
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          
      - name: Fetch Deployment Logs
        id: fetch-logs
        run: |
          DEPLOY_ID=${{ github.event.deployment.id }}
          DEPLOY_URL=${{ github.event.deployment_status.target_url }}
          DEPLOY_STATUS=${{ github.event.deployment_status.state }}
          TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
          
          # Create logs directory if it doesn't exist
          mkdir -p deployment-logs
          
          # Generate log file
          cat << EOF > deployment-logs/deploy_${TIMESTAMP}.md
          # Deployment Log
          
          - **Status**: ${DEPLOY_STATUS}
          - **Deployment ID**: ${DEPLOY_ID}
          - **URL**: ${DEPLOY_URL}
          - **Timestamp**: $(date -u)
          
          ## Build Logs
          \`\`\`
          $(vercel logs ${DEPLOY_ID} --token=${{ secrets.VERCEL_TOKEN }})
          \`\`\`
          
          ## Environment
          - Node.js: $(node -v)
          - NPM: $(npm -v)
          - Vercel CLI: $(vercel -v)
          EOF
          
      - name: Commit and Push Logs
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add deployment-logs/
          git commit -m "📝 Add deployment log for ${{ github.event.deployment_status.state }} deployment"
          git push 